
# tap repositories and their packages

tap homebrew/core
brew ansible
brew binutils
brew cabal-install
brew cfssl
brew circleci
brew coreutils
brew ctags
brew curl
brew dep
brew direnv
brew findutils
brew fzf
brew gcc
brew gdbm
brew gettext
brew ghc
brew ghq
brew gibo
brew git
brew gmp
brew go
brew haskell-stack
brew hr
brew htop
brew hub
brew icu4c
brew isl
brew jemalloc
brew jq
brew jsonnet
brew kubectx
brew kubernetes-cli
brew kustomize
brew libevent
brew libidn2
brew libmpc
brew libtermkey
brew libtool
brew libunistring
brew libuv
brew libvterm
brew libyaml
brew luajit
brew mas
brew mongodb
brew mpfr
brew msgpack
brew mysql
brew neovim
brew nmap
brew node
brew oniguruma
brew openssl
brew peco
brew postgresql
brew protobuf
brew pwgen
brew python@2
brew readline
brew reattach-to-user-namespace
brew redis
brew skaffold
brew socat
brew sqlite
brew telnet
brew tig
brew tmux
brew tmux-cssh
brew tree
brew unibilium
brew watch
brew wget
brew xz
brew zsh

tap homebrew/bundle

tap caskroom/cask

tap kryptco/tap
brew kr

tap rcmdnk/file
brew brew-file

tap vitorgalvao/tiny-scripts
brew cask-repair

# Other Homebrew packages
brew heroku
brew rustup

# Other Cask applications
cask 1password
cask alfred
cask atom
cask boostnote
cask caffeine
cask coteditor
cask dash
cask docker-edge
cask dropbox
cask firefox
cask flux
cask google-cloud-sdk
cask google-japanese-ime
cask intellij-idea
cask istat-menus
cask iterm2
cask karabiner-elements
cask kindle
cask mendeley
cask quik
cask skype
cask slack

# App Store applications
appstore 682658836 GarageBand (10.2.0)
appstore 408981434 iMovie (10.1.8)
appstore 409183694 Keynote (7.3.1)
appstore 539883307 LINE (5.6.1)
appstore 409203825 Numbers (4.3.1)
appstore 409201541 Pages (6.3.1)
appstore 445189367 PopClip (1.5.8)
